import type { OrganizationTypeConfig } from "./organization";

export const ORGANIZATION_CONFIGS: Record<string, OrganizationTypeConfig> = {
  crossfit_box: {
    type: "crossfit_box",
    label: "CrossFit Box",
    icon: "flame",
    description: "CrossFit affiliates and functional fitness boxes",
    terminology: {
      organization: "Box", organizationPlural: "Boxes",
      member: "Athlete", memberPlural: "Athletes",
      instructor: "Coach", instructorPlural: "Coaches",
      session: "Class", sessionPlural: "Classes",
      workout: "WOD", workoutPlural: "WODs",
      result: "Score", record: "PR",
      checkin: "Check-in", booking: "Booking",
    },
    features: {
      wods: true, leaderboard: true, personalRecords: true, rxScaled: true,
      timers: true, rmCalculator: true, gamification: true, fistbumps: true,
      dropins: true, tvDisplay: true, movementLibrary: true, beltSystem: false,
      personalTraining: true, nutritionTracking: false, bodyComposition: true,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["WOD", "Open Box", "Strength", "Gymnastics", "Endurance", "Mobility", "Hyrox"],
  },

  functional_training: {
    type: "functional_training",
    label: "Functional Training",
    icon: "dumbbell",
    description: "Functional training gyms and bootcamp studios",
    terminology: {
      organization: "Gym", organizationPlural: "Gyms",
      member: "Athlete", memberPlural: "Athletes",
      instructor: "Coach", instructorPlural: "Coaches",
      session: "Class", sessionPlural: "Classes",
      workout: "Workout", workoutPlural: "Workouts",
      result: "Score", record: "Personal Best",
      checkin: "Check-in", booking: "Booking",
    },
    features: {
      wods: true, leaderboard: true, personalRecords: true, rxScaled: false,
      timers: true, rmCalculator: true, gamification: true, fistbumps: true,
      dropins: false, tvDisplay: true, movementLibrary: true, beltSystem: false,
      personalTraining: true, nutritionTracking: false, bodyComposition: true,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["HIIT", "Strength", "Conditioning", "Mobility", "Bootcamp"],
  },

  gym: {
    type: "gym",
    label: "Gym",
    icon: "building",
    description: "Traditional gyms and fitness centers",
    terminology: {
      organization: "Gym", organizationPlural: "Gyms",
      member: "Member", memberPlural: "Members",
      instructor: "Trainer", instructorPlural: "Trainers",
      session: "Session", sessionPlural: "Sessions",
      workout: "Workout", workoutPlural: "Workouts",
      result: "Result", record: "Personal Best",
      checkin: "Check-in", booking: "Reservation",
    },
    features: {
      wods: false, leaderboard: false, personalRecords: true, rxScaled: false,
      timers: false, rmCalculator: true, gamification: true, fistbumps: false,
      dropins: false, tvDisplay: false, movementLibrary: true, beltSystem: false,
      personalTraining: true, nutritionTracking: true, bodyComposition: true,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["Group Class", "Personal Training", "Spinning", "Yoga", "Pilates"],
  },

  yoga_studio: {
    type: "yoga_studio",
    label: "Yoga Studio",
    icon: "leaf",
    description: "Yoga studios and meditation centers",
    terminology: {
      organization: "Studio", organizationPlural: "Studios",
      member: "Student", memberPlural: "Students",
      instructor: "Instructor", instructorPlural: "Instructors",
      session: "Class", sessionPlural: "Classes",
      workout: "Flow", workoutPlural: "Flows",
      result: "Practice", record: "Milestone",
      checkin: "Attendance", booking: "Reservation",
    },
    features: {
      wods: false, leaderboard: false, personalRecords: false, rxScaled: false,
      timers: true, rmCalculator: false, gamification: true, fistbumps: false,
      dropins: true, tvDisplay: false, movementLibrary: true, beltSystem: false,
      personalTraining: true, nutritionTracking: false, bodyComposition: false,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["Vinyasa", "Hatha", "Ashtanga", "Yin", "Meditation", "Breathwork"],
  },

  pilates_studio: {
    type: "pilates_studio",
    label: "Pilates Studio",
    icon: "circle-dot",
    description: "Pilates studios with mat and reformer classes",
    terminology: {
      organization: "Studio", organizationPlural: "Studios",
      member: "Client", memberPlural: "Clients",
      instructor: "Instructor", instructorPlural: "Instructors",
      session: "Class", sessionPlural: "Classes",
      workout: "Routine", workoutPlural: "Routines",
      result: "Progress", record: "Milestone",
      checkin: "Attendance", booking: "Reservation",
    },
    features: {
      wods: false, leaderboard: false, personalRecords: false, rxScaled: false,
      timers: false, rmCalculator: false, gamification: true, fistbumps: false,
      dropins: false, tvDisplay: false, movementLibrary: true, beltSystem: false,
      personalTraining: true, nutritionTracking: false, bodyComposition: true,
      groupClasses: true, openGym: false, store: true,
    },
    defaultClassTypes: ["Mat Pilates", "Reformer", "Tower", "Chair", "Private"],
  },

  martial_arts: {
    type: "martial_arts",
    label: "Martial Arts",
    icon: "shield",
    description: "Martial arts dojos, academies, and fight gyms",
    terminology: {
      organization: "Academy", organizationPlural: "Academies",
      member: "Student", memberPlural: "Students",
      instructor: "Sensei", instructorPlural: "Instructors",
      session: "Training", sessionPlural: "Trainings",
      workout: "Kata", workoutPlural: "Katas",
      result: "Performance", record: "Achievement",
      checkin: "Attendance", booking: "Sign-up",
    },
    features: {
      wods: false, leaderboard: true, personalRecords: false, rxScaled: false,
      timers: true, rmCalculator: false, gamification: true, fistbumps: true,
      dropins: false, tvDisplay: false, movementLibrary: true, beltSystem: true,
      personalTraining: true, nutritionTracking: false, bodyComposition: false,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["BJJ", "Muay Thai", "Boxing", "MMA", "Judo", "Karate", "Kids"],
  },

  personal_training: {
    type: "personal_training",
    label: "Personal Training Studio",
    icon: "user",
    description: "PT studios and independent personal trainers",
    terminology: {
      organization: "Studio", organizationPlural: "Studios",
      member: "Client", memberPlural: "Clients",
      instructor: "PT", instructorPlural: "PTs",
      session: "Session", sessionPlural: "Sessions",
      workout: "Program", workoutPlural: "Programs",
      result: "Progress", record: "Personal Best",
      checkin: "Check-in", booking: "Appointment",
    },
    features: {
      wods: false, leaderboard: false, personalRecords: true, rxScaled: false,
      timers: true, rmCalculator: true, gamification: true, fistbumps: false,
      dropins: false, tvDisplay: false, movementLibrary: true, beltSystem: false,
      personalTraining: true, nutritionTracking: true, bodyComposition: true,
      groupClasses: false, openGym: false, store: false,
    },
    defaultClassTypes: ["1:1 Session", "Semi-Private", "Online Coaching", "Assessment"],
  },

  swimming: {
    type: "swimming",
    label: "Swimming Pool",
    icon: "waves",
    description: "Swimming pools, aquatic centers, and swim schools",
    terminology: {
      organization: "Pool", organizationPlural: "Pools",
      member: "Swimmer", memberPlural: "Swimmers",
      instructor: "Coach", instructorPlural: "Coaches",
      session: "Lesson", sessionPlural: "Lessons",
      workout: "Set", workoutPlural: "Sets",
      result: "Time", record: "Personal Best",
      checkin: "Check-in", booking: "Booking",
    },
    features: {
      wods: false, leaderboard: true, personalRecords: true, rxScaled: false,
      timers: true, rmCalculator: false, gamification: true, fistbumps: false,
      dropins: false, tvDisplay: false, movementLibrary: false, beltSystem: false,
      personalTraining: true, nutritionTracking: false, bodyComposition: false,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["Free Swim", "Swim Lesson", "Aqua Fitness", "Kids Swim", "Masters"],
  },

  dance_studio: {
    type: "dance_studio",
    label: "Dance Studio",
    icon: "music",
    description: "Dance studios and performing arts schools",
    terminology: {
      organization: "Studio", organizationPlural: "Studios",
      member: "Dancer", memberPlural: "Dancers",
      instructor: "Teacher", instructorPlural: "Teachers",
      session: "Class", sessionPlural: "Classes",
      workout: "Choreography", workoutPlural: "Choreographies",
      result: "Performance", record: "Achievement",
      checkin: "Attendance", booking: "Reservation",
    },
    features: {
      wods: false, leaderboard: false, personalRecords: false, rxScaled: false,
      timers: false, rmCalculator: false, gamification: true, fistbumps: false,
      dropins: false, tvDisplay: false, movementLibrary: true, beltSystem: true,
      personalTraining: true, nutritionTracking: false, bodyComposition: false,
      groupClasses: true, openGym: false, store: true,
    },
    defaultClassTypes: ["Ballet", "Contemporary", "Hip Hop", "Jazz", "Latin", "Kids"],
  },

  health_club: {
    type: "health_club",
    label: "Health Club",
    icon: "heart-pulse",
    description: "Health clubs, wellness centers, and spa gyms",
    terminology: {
      organization: "Club", organizationPlural: "Clubs",
      member: "Member", memberPlural: "Members",
      instructor: "Trainer", instructorPlural: "Trainers",
      session: "Session", sessionPlural: "Sessions",
      workout: "Program", workoutPlural: "Programs",
      result: "Progress", record: "Personal Best",
      checkin: "Check-in", booking: "Reservation",
    },
    features: {
      wods: false, leaderboard: false, personalRecords: true, rxScaled: false,
      timers: false, rmCalculator: false, gamification: true, fistbumps: false,
      dropins: false, tvDisplay: false, movementLibrary: true, beltSystem: false,
      personalTraining: true, nutritionTracking: true, bodyComposition: true,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["Group Fitness", "Spinning", "Yoga", "Pilates", "Aqua", "PT"],
  },

  sports_club: {
    type: "sports_club",
    label: "Sports Club",
    icon: "trophy",
    description: "Multi-sport clubs, padel centers, tennis clubs",
    terminology: {
      organization: "Club", organizationPlural: "Clubs",
      member: "Player", memberPlural: "Players",
      instructor: "Coach", instructorPlural: "Coaches",
      session: "Session", sessionPlural: "Sessions",
      workout: "Training", workoutPlural: "Trainings",
      result: "Score", record: "Record",
      checkin: "Check-in", booking: "Booking",
    },
    features: {
      wods: false, leaderboard: true, personalRecords: true, rxScaled: false,
      timers: true, rmCalculator: false, gamification: true, fistbumps: true,
      dropins: false, tvDisplay: true, movementLibrary: false, beltSystem: false,
      personalTraining: true, nutritionTracking: false, bodyComposition: false,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["Padel", "Tennis", "Squash", "Badminton", "Training", "Kids"],
  },

  climbing_gym: {
    type: "climbing_gym",
    label: "Climbing Gym",
    icon: "mountain",
    description: "Bouldering gyms, sport climbing walls, and climbing centers",
    terminology: {
      organization: "Gym", organizationPlural: "Gyms",
      member: "Climber", memberPlural: "Climbers",
      instructor: "Coach", instructorPlural: "Coaches",
      session: "Session", sessionPlural: "Sessions",
      workout: "Problem", workoutPlural: "Problems",
      result: "Send", record: "Personal Best",
      checkin: "Check-in", booking: "Booking",
    },
    features: {
      wods: false, leaderboard: true, personalRecords: true, rxScaled: false,
      timers: true, rmCalculator: false, gamification: true, fistbumps: true,
      dropins: true, tvDisplay: false, movementLibrary: true, beltSystem: true,
      personalTraining: true, nutritionTracking: false, bodyComposition: false,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["Bouldering", "Lead Climbing", "Top Rope", "Kids", "Intro Course", "Training"],
  },

  cycling_studio: {
    type: "cycling_studio",
    label: "Cycling / Spinning Studio",
    icon: "bike",
    description: "Indoor cycling studios, spinning classes, and bike training centers",
    terminology: {
      organization: "Studio", organizationPlural: "Studios",
      member: "Rider", memberPlural: "Riders",
      instructor: "Instructor", instructorPlural: "Instructors",
      session: "Ride", sessionPlural: "Rides",
      workout: "Ride", workoutPlural: "Rides",
      result: "Output", record: "Personal Best",
      checkin: "Check-in", booking: "Booking",
    },
    features: {
      wods: false, leaderboard: true, personalRecords: true, rxScaled: false,
      timers: true, rmCalculator: false, gamification: true, fistbumps: true,
      dropins: true, tvDisplay: true, movementLibrary: false, beltSystem: false,
      personalTraining: false, nutritionTracking: false, bodyComposition: false,
      groupClasses: true, openGym: false, store: true,
    },
    defaultClassTypes: ["Endurance", "HIIT Ride", "Hills", "Recovery Ride", "Intro", "Power Zone"],
  },

  running_club: {
    type: "running_club",
    label: "Running Club",
    icon: "footprints",
    description: "Running clubs, track teams, and trail running groups",
    terminology: {
      organization: "Club", organizationPlural: "Clubs",
      member: "Runner", memberPlural: "Runners",
      instructor: "Coach", instructorPlural: "Coaches",
      session: "Run", sessionPlural: "Runs",
      workout: "Session", workoutPlural: "Sessions",
      result: "Time", record: "PR",
      checkin: "Check-in", booking: "Sign-up",
    },
    features: {
      wods: true, leaderboard: true, personalRecords: true, rxScaled: false,
      timers: true, rmCalculator: false, gamification: true, fistbumps: true,
      dropins: false, tvDisplay: false, movementLibrary: false, beltSystem: false,
      personalTraining: true, nutritionTracking: true, bodyComposition: false,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["Easy Run", "Tempo", "Intervals", "Long Run", "Trail", "Track", "Race Prep"],
  },

  gymnastics_academy: {
    type: "gymnastics_academy",
    label: "Gymnastics Academy",
    icon: "star",
    description: "Gymnastics academies for recreational and competitive gymnasts",
    terminology: {
      organization: "Academy", organizationPlural: "Academies",
      member: "Gymnast", memberPlural: "Gymnasts",
      instructor: "Coach", instructorPlural: "Coaches",
      session: "Practice", sessionPlural: "Practices",
      workout: "Routine", workoutPlural: "Routines",
      result: "Score", record: "Personal Best",
      checkin: "Attendance", booking: "Enrollment",
    },
    features: {
      wods: false, leaderboard: true, personalRecords: true, rxScaled: false,
      timers: false, rmCalculator: false, gamification: true, fistbumps: true,
      dropins: false, tvDisplay: false, movementLibrary: true, beltSystem: true,
      personalTraining: true, nutritionTracking: false, bodyComposition: true,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["Recreational", "Competitive", "Tumbling", "Trampoline", "Kids", "Adults"],
  },

  rehabilitation: {
    type: "rehabilitation",
    label: "Rehabilitation / Physiotherapy",
    icon: "heart-handshake",
    description: "Physiotherapy clinics, rehabilitation centers, and recovery studios",
    terminology: {
      organization: "Clinic", organizationPlural: "Clinics",
      member: "Patient", memberPlural: "Patients",
      instructor: "Therapist", instructorPlural: "Therapists",
      session: "Appointment", sessionPlural: "Appointments",
      workout: "Protocol", workoutPlural: "Protocols",
      result: "Progress", record: "Milestone",
      checkin: "Check-in", booking: "Appointment",
    },
    features: {
      wods: false, leaderboard: false, personalRecords: true, rxScaled: false,
      timers: true, rmCalculator: false, gamification: false, fistbumps: false,
      dropins: false, tvDisplay: false, movementLibrary: true, beltSystem: false,
      personalTraining: true, nutritionTracking: false, bodyComposition: true,
      groupClasses: true, openGym: false, store: false,
    },
    defaultClassTypes: ["Individual Session", "Group Rehab", "Assessment", "Follow-up", "Dry Needling"],
  },

  weightlifting_club: {
    type: "weightlifting_club",
    label: "Weightlifting Club",
    icon: "medal",
    description: "Olympic weightlifting clubs and strength sports facilities",
    terminology: {
      organization: "Club", organizationPlural: "Clubs",
      member: "Lifter", memberPlural: "Lifters",
      instructor: "Coach", instructorPlural: "Coaches",
      session: "Session", sessionPlural: "Sessions",
      workout: "Program", workoutPlural: "Programs",
      result: "Total", record: "PR",
      checkin: "Check-in", booking: "Booking",
    },
    features: {
      wods: true, leaderboard: true, personalRecords: true, rxScaled: false,
      timers: true, rmCalculator: true, gamification: true, fistbumps: true,
      dropins: true, tvDisplay: true, movementLibrary: true, beltSystem: false,
      personalTraining: true, nutritionTracking: true, bodyComposition: true,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["Snatch", "Clean & Jerk", "Strength", "Technique", "Competition Prep", "Open Platform"],
  },

  bootcamp: {
    type: "bootcamp",
    label: "Outdoor / Boot Camp",
    icon: "sun",
    description: "Outdoor fitness boot camps, park workouts, and adventure fitness",
    terminology: {
      organization: "Camp", organizationPlural: "Camps",
      member: "Participant", memberPlural: "Participants",
      instructor: "Coach", instructorPlural: "Coaches",
      session: "Session", sessionPlural: "Sessions",
      workout: "Workout", workoutPlural: "Workouts",
      result: "Score", record: "Personal Best",
      checkin: "Check-in", booking: "Sign-up",
    },
    features: {
      wods: true, leaderboard: true, personalRecords: true, rxScaled: false,
      timers: true, rmCalculator: false, gamification: true, fistbumps: true,
      dropins: true, tvDisplay: false, movementLibrary: true, beltSystem: false,
      personalTraining: false, nutritionTracking: false, bodyComposition: false,
      groupClasses: true, openGym: false, store: true,
    },
    defaultClassTypes: ["HIIT", "Strength", "Endurance", "Obstacle Prep", "Morning", "Lunch Express"],
  },

  surf_water_sports: {
    type: "surf_water_sports",
    label: "Surf / Water Sports",
    icon: "waves",
    description: "Surf schools, SUP centers, kayak clubs, and water sports academies",
    terminology: {
      organization: "School", organizationPlural: "Schools",
      member: "Student", memberPlural: "Students",
      instructor: "Instructor", instructorPlural: "Instructors",
      session: "Lesson", sessionPlural: "Lessons",
      workout: "Session", workoutPlural: "Sessions",
      result: "Progress", record: "Achievement",
      checkin: "Check-in", booking: "Booking",
    },
    features: {
      wods: false, leaderboard: false, personalRecords: false, rxScaled: false,
      timers: false, rmCalculator: false, gamification: true, fistbumps: true,
      dropins: true, tvDisplay: false, movementLibrary: true, beltSystem: true,
      personalTraining: true, nutritionTracking: false, bodyComposition: false,
      groupClasses: true, openGym: false, store: true,
    },
    defaultClassTypes: ["Surf Lesson", "SUP", "Kayak", "Bodyboard", "Advanced", "Kids", "Private"],
  },

  other: {
    type: "other",
    label: "Other",
    icon: "plus-circle",
    description: "Custom space — configure everything yourself",
    terminology: {
      organization: "Space", organizationPlural: "Spaces",
      member: "Member", memberPlural: "Members",
      instructor: "Instructor", instructorPlural: "Instructors",
      session: "Class", sessionPlural: "Classes",
      workout: "Workout", workoutPlural: "Workouts",
      result: "Result", record: "Record",
      checkin: "Check-in", booking: "Booking",
    },
    features: {
      wods: true, leaderboard: true, personalRecords: true, rxScaled: true,
      timers: true, rmCalculator: true, gamification: true, fistbumps: true,
      dropins: true, tvDisplay: true, movementLibrary: true, beltSystem: true,
      personalTraining: true, nutritionTracking: true, bodyComposition: true,
      groupClasses: true, openGym: true, store: true,
    },
    defaultClassTypes: ["Class", "Session", "Training"],
  },
};

export const ORGANIZATION_TYPE_LIST = Object.values(ORGANIZATION_CONFIGS);
