// ── Multi-language ──────────────────────────────────────────────────────────
export type Lang = "pt" | "en" | "es";

export const LANDING_COPY: Record<Lang, Record<string, string>> = {
  pt: {
    badge: "A plataforma #1 para espaços fitness em Portugal",
    headline: "Gerir o seu espaço fitness nunca foi tão simples",
    subtitle: "Membros, aulas, pagamentos, CRM, website — tudo numa única plataforma. De CrossFit a Yoga, de PT a Artes Marciais.",
    ctaStart: "Começar Grátis",
    ctaDemo: "Ver Demo",
    signIn: "Entrar",
    features: "Funcionalidades",
    pricing: "Preços",
    testimonials: "Testemunhos",
    faq: "FAQ",
    statVerticals: "Verticais",
    statFeatures: "Funcionalidades",
    statLangs: "Idiomas",
    statLocal: "100% Português",
    trustedBy: "Confiado por espaços em todo o país",
    everythingTitle: "Tudo o que precisa. Numa plataforma.",
    everythingSubtitle: "Construído de raiz para o mercado português, com todas as ferramentas que o seu espaço fitness precisa para crescer.",
    feat1: "Gestão de Membros", feat1d: "Perfis completos, histórico de presenças, planos de pagamento, documentos RGPD e comunicação integrada.",
    feat2: "Aulas & Horários", feat2d: "Calendário inteligente com reservas online, listas de espera, capacidade máxima e notificações automáticas.",
    feat3: "WODs & Treinos", feat3d: "Construtor de WODs com biblioteca de exercícios, tracking de resultados e progressão dos atletas.",
    feat4: "CRM & Leads", feat4d: "Pipeline drag-and-drop, follow-ups automáticos, conversão de leads e análise do funil de vendas.",
    feat5: "Finanças & Pagamentos", feat5d: "MBWay, SEPA, referências Multibanco, SAF-T, ATCUD, faturas automáticas e relatórios fiscais.",
    feat6: "Website & Loja", feat6d: "Site público personalizável com domínio próprio, loja online, landing pages e SEO integrado.",
    featLearnMore: "Saber mais",
    showcaseTitle: "Uma plataforma,",
    showcaseTitleHighlight: "múltiplas experiências",
    showcaseSubtitle: "Para gestores, atletas e visitantes — cada um tem a interface perfeita.",
    showcaseBadge: "Produto",
    showcaseExplore: "Explorar",
    compTitle: "Porquê o Vytal?",
    compSubtitle: "Construído especificamente para o mercado português, com funcionalidades que os concorrentes simplesmente não têm.",
    compBadge: "Comparação",
    compColFeature: "Funcionalidade",
    compGeneric: "Genérico",
    compRow1: "Multi-vertical (20+ tipos de espaço)",
    compRow2: "Totalmente em Português (PT)",
    compRow3: "Website público personalizável",
    compRow4: "App Mobile nativa",
    compRow5: "MBWay & Multibanco",
    compRow6: "SAF-T & ATCUD (Portugal)",
    compRow7: "AI Insights & Recomendações",
    compRow8: "API Aberta & Integrações",
    testimonialsTitle: "O que dizem os nossos",
    testimonialsTitleHighlight: "clientes",
    testimonialsBadge: "Testemunhos",
    t1quote: "Desde que mudámos para o Vytal, poupamos 3 horas por dia em tarefas administrativas. Os pagamentos automáticos via MBWay mudaram completamente o nosso fluxo de caixa.",
    t1name: "Ana Ferreira", t1role: "Proprietária", t1gym: "CrossFit Aveiro",
    t2quote: "O CRM de leads é incrível. Antes perdíamos potenciais membros porque não tínhamos follow-up. Agora convertemos 40% mais leads em membros pagantes.",
    t2name: "Ricardo Santos", t2role: "Head Coach & Manager", t2gym: "Iron Temple Lisboa",
    t3quote: "Gerimos 3 estúdios de yoga com o Vytal. A funcionalidade multi-localização é fantástica e o website personalizado para cada estúdio aumentou as nossas inscrições em 60%.",
    t3name: "Sofia Maia", t3role: "Directora", t3gym: "Studio Zen — 3 locais",
    pricingTitle: "Simples e",
    pricingTitleHighlight: "transparente",
    pricingSubtitle: "Sem surpresas, sem custos escondidos. Mude de plano quando quiser.",
    pricingBadge: "Preços",
    monthly: "Mensal",
    annual: "Anual",
    mostPopular: "Mais Popular",
    onRequest: "Sob consulta",
    billedAnnually: "Facturado anualmente · Poupa",
    perYear: "€/ano",
    pricingNote: "Sem cartão de crédito necessário para começar · Cancele quando quiser · Suporte em Português",
    planFreeDesc: "Para começar sem compromisso.",
    planProDesc: "Para espaços em crescimento.",
    planEnterpriseDesc: "Para redes e franquias fitness.",
    planFreePeriod: "para sempre",
    planProPeriod: "por mês",
    planEnterprisePeriod: "personalizado",
    planFreeF1: "Até 20 membros", planFreeF2: "1 localização", planFreeF3: "Calendário de aulas",
    planFreeF4: "Perfis básicos", planFreeF5: "App mobile (leitura)", planFreeF6: "Suporte por email",
    planFreeN1: "Pagamentos automáticos", planFreeN2: "CRM avançado", planFreeN3: "Website público", planFreeN4: "API",
    planProF1: "Membros ilimitados", planProF2: "1 localização", planProF3: "Todas as funcionalidades",
    planProF4: "Website público personalizado", planProF5: "Pagamentos MBWay & SEPA", planProF6: "SAF-T & ATCUD",
    planProF7: "CRM & Leads", planProF8: "App mobile completa", planProF9: "Suporte prioritário",
    planProN1: "Multi-localização", planProN2: "API Aberta",
    planEntF1: "Multi-localização", planEntF2: "Membros ilimitados", planEntF3: "API Aberta & Webhooks",
    planEntF4: "Integrações personalizadas", planEntF5: "Suporte dedicado 24/7", planEntF6: "Onboarding assistido",
    planEntF7: "SLA garantido", planEntF8: "Facturação centralizada",
    planFreeCta: "Começar Grátis", planProCta: "Começar Grátis 14 dias", planEntCta: "Falar com Vendas",
    faqTitle: "Perguntas",
    faqTitleHighlight: "frequentes",
    faqBadge: "FAQ",
    faq1q: "O Vytal funciona para yoga, pilates, artes marciais e outros tipos de espaço?",
    faq1a: "Sim! O Vytal suporta 20+ tipos de espaços fitness e wellness, incluindo CrossFit, yoga, pilates, artes marciais, natação, ginásios tradicionais, personal trainers, estúdios de dança e muito mais. Cada vertical tem as suas configurações e terminologia própria.",
    faq2q: "Posso migrar o meu espaço do Regibox ou outro software?",
    faq2a: "Absolutamente. Temos uma equipa de onboarding dedicada que ajuda na migração de dados (membros, pagamentos, histórico) de qualquer plataforma anterior. A migração é gratuita nos planos Pro e Enterprise e normalmente demora menos de 48 horas.",
    faq3q: "O site público do meu espaço é totalmente personalizável?",
    faq3a: "Sim. Cada espaço tem o seu próprio subdomínio (vytal.fit/o-meu-ginasio) ou pode usar o seu domínio próprio. Pode personalizar cores, logo, fotos, textos, horários, preços e muito mais — sem precisar de conhecimentos técnicos.",
    faq4q: "Quais métodos de pagamento são suportados?",
    faq4a: "Suportamos MBWay, referências Multibanco, transferência SEPA, cartão de crédito/débito e débito direto. Para o mercado português, geramos SAF-T e ATCUD conformes com a AT. Em breve também PayPal e Apple Pay.",
    faq5q: "Existe uma app mobile para os atletas?",
    faq5a: "Sim, a app Vytal está disponível para iOS (App Store) e Android (Google Play). Os atletas podem fazer check-in, consultar WODs, ver o seu progresso, fazer reservas e comunicar com os seus coaches diretamente pela app.",
    faq6q: "O Vytal cumpre com o RGPD (Regulamento Geral de Proteção de Dados)?",
    faq6a: "Totalmente. Todos os dados são alojados na União Europeia (Portugal/Irlanda), com encriptação end-to-end, controlo de acessos por perfil, registo de consentimentos, direito ao esquecimento e exportação de dados. Disponibilizamos DPA (Data Processing Agreement) para todos os clientes.",
    ctaBannerBadge: "Sem cartão de crédito",
    ctaBannerTitle: "Pronto para transformar",
    ctaBannerTitleLine2: "o seu espaço?",
    ctaBannerSubtitle: "Comece grátis hoje. Configure o seu espaço em menos de 5 minutos. Sem compromisso, sem cartão de crédito.",
    ctaBannerStart: "Começar Grátis Agora",
    ctaBannerDemo: "Ver Demo ao Vivo",
    footerTagline: "A plataforma de gestão para espaços fitness e wellness — feita em Portugal, para o mundo.",
    footerRights: "Todos os direitos reservados. Feito com",
    footerInPortugal: "em Portugal.",
    footerAllSystems: "Todos os sistemas operacionais",
    footerProduct: "Produto", footerResources: "Recursos", footerCompany: "Empresa", footerLegal: "Legal",
    fpFeat: "Funcionalidades", fpPricing: "Preços", fpNews: "Novidades", fpRoadmap: "Roadmap", fpApi: "API Docs",
    frHelp: "Centro de Ajuda", frBlog: "Blog", frVideos: "Tutoriais em Vídeo", frBrand: "Marca", frStatus: "Estado do Sistema",
    fcAbout: "Sobre Nós", fcCareers: "Carreiras", fcPartners: "Parceiros", fcPress: "Imprensa", fcContact: "Contacto",
    flTerms: "Termos de Serviço", flPrivacy: "Política de Privacidade", flRgpd: "RGPD", flCookies: "Cookies", flDpa: "DPA",
    tabAdmin: "Admin", tabWebsite: "Website", tabMembro: "Membro", tabMobile: "Mobile",
    tabAdminTitle: "Painel de controlo completo",
    tabAdminDesc: "Uma visão 360° do seu espaço. Dashboards em tempo real, gestão de membros, finanças e muito mais — tudo num só lugar.",
    tabAdminI1: "Dashboard", tabAdminI2: "Membros", tabAdminI3: "Aulas", tabAdminI4: "CRM", tabAdminI5: "Finanças", tabAdminI6: "Relatórios",
    tabWebsiteTitle: "Site público personalizável",
    tabWebsiteDesc: "Cada espaço tem o seu site com domínio próprio, cores da marca, horários ao vivo, loja e formulário de contacto.",
    tabWebsiteI1: "Página Inicial", tabWebsiteI2: "Horários", tabWebsiteI3: "Planos", tabWebsiteI4: "Instrutores", tabWebsiteI5: "Loja", tabWebsiteI6: "Contacto",
    tabMembroTitle: "Portal do atleta",
    tabMembroDesc: "Os seus membros acedem online para ver horários, fazer reservas, consultar resultados e gerir a sua subscrição.",
    tabMembroI1: "As Minhas Aulas", tabMembroI2: "Resultados", tabMembroI3: "Plano", tabMembroI4: "Pagamentos", tabMembroI5: "Perfil", tabMembroI6: "Progresso",
    tabMobileTitle: "App para iOS e Android",
    tabMobileDesc: "Os atletas levam o ginásio no bolso. Check-in, treinos, resultados e comunicações — tudo na app Vytal.",
    tabMobileI1: "Today's WOD", tabMobileI2: "Check-in", tabMobileI3: "Leaderboard", tabMobileI4: "Treinos", tabMobileI5: "Mensagens", tabMobileI6: "Progresso",
    // Verticals
    verticalsTitle: "Um produto.",
    verticalsTitleHighlight: "20 verticais.",
    verticalsSubtitle: "Da box de CrossFit ao estúdio de dança — o Vytal adapta-se ao seu negócio.",
    v_crossfit_box: "CrossFit Box",
    v_functional_training: "Treino Funcional",
    v_gym: "Ginásio",
    v_yoga_studio: "Estúdio de Yoga",
    v_pilates_studio: "Estúdio de Pilates",
    v_martial_arts: "Artes Marciais",
    v_personal_training: "Personal Training",
    v_swimming: "Natação",
    v_dance_studio: "Estúdio de Dança",
    v_health_club: "Health Club",
    v_sports_club: "Clube Desportivo",
    v_climbing_gym: "Ginásio de Escalada",
    v_cycling_studio: "Estúdio de Cycling",
    v_running_club: "Clube de Corrida",
    v_gymnastics_academy: "Academia de Ginástica",
    v_rehabilitation: "Reabilitação",
    v_weightlifting_club: "Clube de Halterofilia",
    v_bootcamp: "Bootcamp",
    v_surf_water_sports: "Surf & Desportos Aquáticos",
    v_other: "Outro",
    // Feature Deep Dive
    deepDiveBadge: "Funcionalidades em detalhe",
    deepDiveCheckinTitle: "Check-in inteligente",
    deepDiveCheckinDesc: "Elimine as filas e o papel. O check-in é instantâneo, preciso e integrado com presenças e pagamentos.",
    deepDiveCheckinB1: "QR Code único por atleta",
    deepDiveCheckinB2: "Check-in em massa para coaches",
    deepDiveCheckinB3: "Walk-in sem reserva prévia",
    deepDiveCheckinB4: "Tracking de no-shows automático",
    deepDiveCrmTitle: "CRM & Pipeline de vendas",
    deepDiveCrmDesc: "Converta mais leads em membros pagantes com um pipeline visual e follow-ups automáticos.",
    deepDiveCrmB1: "Kanban drag-and-drop intuitivo",
    deepDiveCrmB2: "Lead scoring automático",
    deepDiveCrmB3: "Rastreio de fonte (Facebook, Google...)",
    deepDiveCrmB4: "Follow-up automático por email/SMS",
    deepDiveWebsiteTitle: "Website builder completo",
    deepDiveWebsiteDesc: "O seu espaço merece uma presença digital profissional. Configure em minutos, sem código.",
    deepDiveWebsiteB1: "Domínio próprio incluído",
    deepDiveWebsiteB2: "6 páginas: Home, Horários, Planos, Equipa, Loja, Contacto",
    deepDiveWebsiteB3: "Loja online com carrinho de compras",
    deepDiveWebsiteB4: "SEO, analytics e testemunhos integrados",
    deepDiveAnalyticsTitle: "Relatórios & Analytics",
    deepDiveAnalyticsDesc: "Tome decisões baseadas em dados reais. Veja o que funciona e corrija o que não funciona.",
    deepDiveAnalyticsB1: "Heatmap de presenças por hora/dia",
    deepDiveAnalyticsB2: "Gráficos de receita e crescimento",
    deepDiveAnalyticsB3: "Previsão de churn com IA",
    deepDiveAnalyticsB4: "Análise de retenção de membros",
    // Payments
    paymentsTitle: "Pagamentos",
    paymentsTitleHighlight: "Portugal",
    paymentsBadge: "Pagamentos",
    paymentsSubtitle: "Todos os métodos de pagamento que os seus clientes utilizam — integrados de raiz.",
    paymentsMbway: "MB Way",
    paymentsMultibanco: "Multibanco",
    paymentsSepa: "SEPA",
    paymentsVisa: "Visa / MC",
    paymentsCash: "Numerário",
    paymentsTransfer: "Transferência",
    // Automations & AI
    autoTitle: "Automações &",
    autoTitleHighlight: "Inteligência Artificial",
    autoBadge: "Automações & AI",
    autoSubtitle: "Poupe horas por semana com automações inteligentes e insights gerados por IA.",
    autoColLeft: "Automações",
    autoColRight: "AI Insights",
    autoA1Title: "Emails de milestone", autoA1Desc: "Parabéns automáticos ao 1º mês, 6 meses, 1 ano de membro.",
    autoA2Title: "Campanhas anti-churn", autoA2Desc: "Detecta membros em risco e envia ofertas personalizadas.",
    autoA3Title: "Onboarding sequenciado", autoA3Desc: "Sequência automática de boas-vindas para novos membros.",
    autoA4Title: "Mensagens de aniversário", autoA4Desc: "Felicita automaticamente no dia de aniversário do membro.",
    autoB1Title: "Previsão de churn", autoB1Desc: "IA identifica membros que podem cancelar nas próximas semanas.",
    autoB2Title: "Agendamento inteligente", autoB2Desc: "Sugere os melhores horários com base na procura histórica.",
    autoB3Title: "Sugestão de WODs", autoB3Desc: "Recomenda treinos adaptados ao nível e histórico de cada atleta.",
    autoB4Title: "Readiness scoring", autoB4Desc: "Avalia a prontidão do atleta com base em treinos e recuperação.",
    // Compliance
    complianceTitle: "Compliance &",
    complianceTitleHighlight: "Segurança",
    complianceBadge: "Segurança",
    complianceSubtitle: "Construído para cumprir as exigências legais portuguesas e europeias.",
    complianceRgpd: "RGPD Compliant",
    complianceSaft: "SAF-T / ATCUD Ready",
    complianceSsl: "SSL Encriptado",
    complianceUptime: "99.9% Uptime",
    complianceIso: "ISO 27001 (planeado)",
    complianceBackup: "Backups Diários",
  },
  en: {
    badge: "The #1 platform for fitness spaces in Portugal",
    headline: "Managing your fitness space has never been easier",
    subtitle: "Members, classes, payments, CRM, website — everything in one platform. From CrossFit to Yoga, PT to Martial Arts.",
    ctaStart: "Start Free",
    ctaDemo: "View Demo",
    signIn: "Sign In",
    features: "Features",
    pricing: "Pricing",
    testimonials: "Testimonials",
    faq: "FAQ",
    statVerticals: "Verticals",
    statFeatures: "Features",
    statLangs: "Languages",
    statLocal: "100% Portuguese",
    trustedBy: "Trusted by spaces across the country",
    everythingTitle: "Everything you need. One platform.",
    everythingSubtitle: "Built from the ground up for the Portuguese market, with all the tools your fitness space needs to grow.",
    feat1: "Member Management", feat1d: "Full profiles, attendance history, payment plans, GDPR documents and integrated communication.",
    feat2: "Classes & Schedules", feat2d: "Smart calendar with online bookings, waitlists, max capacity and automatic notifications.",
    feat3: "WODs & Workouts", feat3d: "WOD builder with exercise library, result tracking and athlete progression.",
    feat4: "CRM & Leads", feat4d: "Drag-and-drop pipeline, automatic follow-ups, lead conversion and sales funnel analysis.",
    feat5: "Finance & Payments", feat5d: "MBWay, SEPA, Multibanco references, SAF-T, ATCUD, automatic invoices and tax reports.",
    feat6: "Website & Store", feat6d: "Customizable public site with own domain, online store, landing pages and integrated SEO.",
    featLearnMore: "Learn more",
    showcaseTitle: "One platform,",
    showcaseTitleHighlight: "multiple experiences",
    showcaseSubtitle: "For managers, athletes and visitors — each gets the perfect interface.",
    showcaseBadge: "Product",
    showcaseExplore: "Explore",
    compTitle: "Why Vytal?",
    compSubtitle: "Built specifically for the Portuguese market, with features competitors simply don't have.",
    compBadge: "Comparison",
    compColFeature: "Feature",
    compGeneric: "Generic",
    compRow1: "Multi-vertical (20+ space types)",
    compRow2: "Fully in Portuguese (PT)",
    compRow3: "Customizable public website",
    compRow4: "Native mobile app",
    compRow5: "MBWay & Multibanco",
    compRow6: "SAF-T & ATCUD (Portugal)",
    compRow7: "AI Insights & Recommendations",
    compRow8: "Open API & Integrations",
    testimonialsTitle: "What our",
    testimonialsTitleHighlight: "clients say",
    testimonialsBadge: "Testimonials",
    t1quote: "Since we switched to Vytal, we save 3 hours a day on admin tasks. Automatic payments via MBWay completely changed our cash flow.",
    t1name: "Ana Ferreira", t1role: "Owner", t1gym: "CrossFit Aveiro",
    t2quote: "The leads CRM is amazing. Before, we were losing potential members because we had no follow-up. Now we convert 40% more leads into paying members.",
    t2name: "Ricardo Santos", t2role: "Head Coach & Manager", t2gym: "Iron Temple Lisboa",
    t3quote: "We manage 3 yoga studios with Vytal. The multi-location feature is fantastic and the custom website for each studio increased our sign-ups by 60%.",
    t3name: "Sofia Maia", t3role: "Director", t3gym: "Studio Zen — 3 locations",
    pricingTitle: "Simple and",
    pricingTitleHighlight: "transparent",
    pricingSubtitle: "No surprises, no hidden costs. Change your plan whenever you want.",
    pricingBadge: "Pricing",
    monthly: "Monthly",
    annual: "Annual",
    mostPopular: "Most Popular",
    onRequest: "On request",
    billedAnnually: "Billed annually · Save",
    perYear: "€/yr",
    pricingNote: "No credit card required to start · Cancel anytime · Support in Portuguese",
    planFreeDesc: "To get started with no commitment.",
    planProDesc: "For growing spaces.",
    planEnterpriseDesc: "For fitness networks and franchises.",
    planFreePeriod: "forever",
    planProPeriod: "per month",
    planEnterprisePeriod: "custom",
    planFreeF1: "Up to 20 members", planFreeF2: "1 location", planFreeF3: "Class calendar",
    planFreeF4: "Basic profiles", planFreeF5: "Mobile app (read-only)", planFreeF6: "Email support",
    planFreeN1: "Automatic payments", planFreeN2: "Advanced CRM", planFreeN3: "Public website", planFreeN4: "API",
    planProF1: "Unlimited members", planProF2: "1 location", planProF3: "All features",
    planProF4: "Custom public website", planProF5: "MBWay & SEPA payments", planProF6: "SAF-T & ATCUD",
    planProF7: "CRM & Leads", planProF8: "Full mobile app", planProF9: "Priority support",
    planProN1: "Multi-location", planProN2: "Open API",
    planEntF1: "Multi-location", planEntF2: "Unlimited members", planEntF3: "Open API & Webhooks",
    planEntF4: "Custom integrations", planEntF5: "Dedicated 24/7 support", planEntF6: "Assisted onboarding",
    planEntF7: "Guaranteed SLA", planEntF8: "Centralized billing",
    planFreeCta: "Start Free", planProCta: "Start 14-day Free Trial", planEntCta: "Talk to Sales",
    faqTitle: "Frequently asked",
    faqTitleHighlight: "questions",
    faqBadge: "FAQ",
    faq1q: "Does Vytal work for yoga, pilates, martial arts and other space types?",
    faq1a: "Yes! Vytal supports 20+ types of fitness and wellness spaces, including CrossFit, yoga, pilates, martial arts, swimming, traditional gyms, personal trainers, dance studios and much more. Each vertical has its own settings and terminology.",
    faq2q: "Can I migrate my space from Regibox or other software?",
    faq2a: "Absolutely. We have a dedicated onboarding team that helps with data migration (members, payments, history) from any previous platform. Migration is free on Pro and Enterprise plans and usually takes less than 48 hours.",
    faq3q: "Is my space's public site fully customizable?",
    faq3a: "Yes. Each space gets its own subdomain (vytal.fit/my-gym) or you can use your own domain. You can customize colors, logo, photos, texts, schedules, pricing and much more — no technical knowledge needed.",
    faq4q: "Which payment methods are supported?",
    faq4a: "We support MBWay, Multibanco references, SEPA transfer, credit/debit card and direct debit. For the Portuguese market, we generate SAF-T and ATCUD compliant with AT. PayPal and Apple Pay coming soon.",
    faq5q: "Is there a mobile app for athletes?",
    faq5a: "Yes, the Vytal app is available for iOS (App Store) and Android (Google Play). Athletes can check in, view WODs, track their progress, make bookings and communicate with their coaches directly through the app.",
    faq6q: "Does Vytal comply with GDPR (General Data Protection Regulation)?",
    faq6a: "Fully. All data is hosted in the European Union (Portugal/Ireland), with end-to-end encryption, role-based access control, consent logging, right to erasure and data export. We provide a DPA (Data Processing Agreement) for all clients.",
    ctaBannerBadge: "No credit card",
    ctaBannerTitle: "Ready to transform",
    ctaBannerTitleLine2: "your space?",
    ctaBannerSubtitle: "Start free today. Set up your space in under 5 minutes. No commitment, no credit card.",
    ctaBannerStart: "Start Free Now",
    ctaBannerDemo: "View Live Demo",
    footerTagline: "The management platform for fitness and wellness spaces — made in Portugal, for the world.",
    footerRights: "All rights reserved. Made with",
    footerInPortugal: "in Portugal.",
    footerAllSystems: "All systems operational",
    footerProduct: "Product", footerResources: "Resources", footerCompany: "Company", footerLegal: "Legal",
    fpFeat: "Features", fpPricing: "Pricing", fpNews: "What's New", fpRoadmap: "Roadmap", fpApi: "API Docs",
    frHelp: "Help Center", frBlog: "Blog", frVideos: "Video Tutorials", frBrand: "Brand", frStatus: "System Status",
    fcAbout: "About Us", fcCareers: "Careers", fcPartners: "Partners", fcPress: "Press", fcContact: "Contact",
    flTerms: "Terms of Service", flPrivacy: "Privacy Policy", flRgpd: "GDPR", flCookies: "Cookies", flDpa: "DPA",
    tabAdmin: "Admin", tabWebsite: "Website", tabMembro: "Member", tabMobile: "Mobile",
    tabAdminTitle: "Complete control panel",
    tabAdminDesc: "A 360° view of your space. Real-time dashboards, member management, finances and much more — all in one place.",
    tabAdminI1: "Dashboard", tabAdminI2: "Members", tabAdminI3: "Classes", tabAdminI4: "CRM", tabAdminI5: "Finances", tabAdminI6: "Reports",
    tabWebsiteTitle: "Customizable public site",
    tabWebsiteDesc: "Each space has its own site with custom domain, brand colors, live schedules, store and contact form.",
    tabWebsiteI1: "Home", tabWebsiteI2: "Schedules", tabWebsiteI3: "Plans", tabWebsiteI4: "Coaches", tabWebsiteI5: "Store", tabWebsiteI6: "Contact",
    tabMembroTitle: "Athlete portal",
    tabMembroDesc: "Your members access online to view schedules, make bookings, check results and manage their subscription.",
    tabMembroI1: "My Classes", tabMembroI2: "Results", tabMembroI3: "Plan", tabMembroI4: "Payments", tabMembroI5: "Profile", tabMembroI6: "Progress",
    tabMobileTitle: "App for iOS and Android",
    tabMobileDesc: "Athletes take the gym in their pocket. Check-in, workouts, results and communications — all in the Vytal app.",
    tabMobileI1: "Today's WOD", tabMobileI2: "Check-in", tabMobileI3: "Leaderboard", tabMobileI4: "Workouts", tabMobileI5: "Messages", tabMobileI6: "Progress",
    // Verticals
    verticalsTitle: "One product.",
    verticalsTitleHighlight: "20 verticals.",
    verticalsSubtitle: "From CrossFit box to dance studio — Vytal adapts to your business.",
    v_crossfit_box: "CrossFit Box",
    v_functional_training: "Functional Training",
    v_gym: "Gym",
    v_yoga_studio: "Yoga Studio",
    v_pilates_studio: "Pilates Studio",
    v_martial_arts: "Martial Arts",
    v_personal_training: "Personal Training",
    v_swimming: "Swimming",
    v_dance_studio: "Dance Studio",
    v_health_club: "Health Club",
    v_sports_club: "Sports Club",
    v_climbing_gym: "Climbing Gym",
    v_cycling_studio: "Cycling Studio",
    v_running_club: "Running Club",
    v_gymnastics_academy: "Gymnastics Academy",
    v_rehabilitation: "Rehabilitation",
    v_weightlifting_club: "Weightlifting Club",
    v_bootcamp: "Bootcamp",
    v_surf_water_sports: "Surf & Water Sports",
    v_other: "Other",
    // Feature Deep Dive
    deepDiveBadge: "Features in detail",
    deepDiveCheckinTitle: "Smart check-in",
    deepDiveCheckinDesc: "Eliminate queues and paperwork. Check-in is instant, accurate and integrated with attendance and payments.",
    deepDiveCheckinB1: "Unique QR Code per athlete",
    deepDiveCheckinB2: "Bulk check-in for coaches",
    deepDiveCheckinB3: "Walk-in without prior booking",
    deepDiveCheckinB4: "Automatic no-show tracking",
    deepDiveCrmTitle: "CRM & Sales pipeline",
    deepDiveCrmDesc: "Convert more leads into paying members with a visual pipeline and automatic follow-ups.",
    deepDiveCrmB1: "Intuitive drag-and-drop kanban",
    deepDiveCrmB2: "Automatic lead scoring",
    deepDiveCrmB3: "Source tracking (Facebook, Google...)",
    deepDiveCrmB4: "Automatic email/SMS follow-up",
    deepDiveWebsiteTitle: "Complete website builder",
    deepDiveWebsiteDesc: "Your space deserves a professional digital presence. Set up in minutes, no code needed.",
    deepDiveWebsiteB1: "Own domain included",
    deepDiveWebsiteB2: "6 pages: Home, Schedule, Plans, Team, Shop, Contact",
    deepDiveWebsiteB3: "Online store with shopping cart",
    deepDiveWebsiteB4: "SEO, analytics and testimonials built in",
    deepDiveAnalyticsTitle: "Reports & Analytics",
    deepDiveAnalyticsDesc: "Make decisions based on real data. See what works and fix what doesn't.",
    deepDiveAnalyticsB1: "Attendance heatmap by hour/day",
    deepDiveAnalyticsB2: "Revenue and growth charts",
    deepDiveAnalyticsB3: "AI-powered churn prediction",
    deepDiveAnalyticsB4: "Member retention analysis",
    // Payments
    paymentsTitle: "Payments for",
    paymentsTitleHighlight: "Portugal",
    paymentsBadge: "Payments",
    paymentsSubtitle: "All payment methods your clients use — integrated from the ground up.",
    paymentsMbway: "MB Way",
    paymentsMultibanco: "Multibanco",
    paymentsSepa: "SEPA",
    paymentsVisa: "Visa / MC",
    paymentsCash: "Cash",
    paymentsTransfer: "Transfer",
    // Automations & AI
    autoTitle: "Automations &",
    autoTitleHighlight: "Artificial Intelligence",
    autoBadge: "Automations & AI",
    autoSubtitle: "Save hours per week with smart automations and AI-generated insights.",
    autoColLeft: "Automations",
    autoColRight: "AI Insights",
    autoA1Title: "Milestone emails", autoA1Desc: "Automatic congratulations at 1st month, 6 months, 1 year as a member.",
    autoA2Title: "Anti-churn campaigns", autoA2Desc: "Detects at-risk members and sends personalized offers.",
    autoA3Title: "Sequenced onboarding", autoA3Desc: "Automatic welcome sequence for new members.",
    autoA4Title: "Birthday messages", autoA4Desc: "Automatically greets members on their birthday.",
    autoB1Title: "Churn prediction", autoB1Desc: "AI identifies members likely to cancel in the coming weeks.",
    autoB2Title: "Smart scheduling", autoB2Desc: "Suggests the best time slots based on historical demand.",
    autoB3Title: "WOD suggestions", autoB3Desc: "Recommends workouts tailored to each athlete's level and history.",
    autoB4Title: "Readiness scoring", autoB4Desc: "Evaluates athlete readiness based on training and recovery data.",
    // Compliance
    complianceTitle: "Compliance &",
    complianceTitleHighlight: "Security",
    complianceBadge: "Security",
    complianceSubtitle: "Built to meet Portuguese and European legal requirements.",
    complianceRgpd: "GDPR Compliant",
    complianceSaft: "SAF-T / ATCUD Ready",
    complianceSsl: "SSL Encrypted",
    complianceUptime: "99.9% Uptime",
    complianceIso: "ISO 27001 (planned)",
    complianceBackup: "Daily Backups",
  },
  es: {
    badge: "La plataforma #1 para espacios fitness en Portugal",
    headline: "Gestionar tu espacio fitness nunca fue tan fácil",
    subtitle: "Miembros, clases, pagos, CRM, sitio web — todo en una plataforma. De CrossFit a Yoga, de PT a Artes Marciales.",
    ctaStart: "Empezar Gratis",
    ctaDemo: "Ver Demo",
    signIn: "Entrar",
    features: "Funcionalidades",
    pricing: "Precios",
    testimonials: "Testimonios",
    faq: "FAQ",
    statVerticals: "Verticales",
    statFeatures: "Funcionalidades",
    statLangs: "Idiomas",
    statLocal: "100% Portugués",
    trustedBy: "La confianza de espacios en todo el país",
    everythingTitle: "Todo lo que necesitas. Una plataforma.",
    everythingSubtitle: "Construido desde cero para el mercado portugués, con todas las herramientas que tu espacio fitness necesita para crecer.",
    feat1: "Gestión de Miembros", feat1d: "Perfiles completos, historial de asistencia, planes de pago, documentos RGPD y comunicación integrada.",
    feat2: "Clases & Horarios", feat2d: "Calendario inteligente con reservas online, listas de espera, capacidad máxima y notificaciones automáticas.",
    feat3: "WODs & Entrenamientos", feat3d: "Constructor de WODs con biblioteca de ejercicios, seguimiento de resultados y progresión de atletas.",
    feat4: "CRM & Leads", feat4d: "Pipeline drag-and-drop, seguimientos automáticos, conversión de leads y análisis del embudo de ventas.",
    feat5: "Finanzas & Pagos", feat5d: "MBWay, SEPA, referencias Multibanco, SAF-T, ATCUD, facturas automáticas e informes fiscales.",
    feat6: "Sitio Web & Tienda", feat6d: "Sitio público personalizable con dominio propio, tienda online, landing pages y SEO integrado.",
    featLearnMore: "Saber más",
    showcaseTitle: "Una plataforma,",
    showcaseTitleHighlight: "múltiples experiencias",
    showcaseSubtitle: "Para gestores, atletas y visitantes — cada uno tiene la interfaz perfecta.",
    showcaseBadge: "Producto",
    showcaseExplore: "Explorar",
    compTitle: "¿Por qué Vytal?",
    compSubtitle: "Construido específicamente para el mercado portugués, con funcionalidades que los competidores simplemente no tienen.",
    compBadge: "Comparación",
    compColFeature: "Funcionalidad",
    compGeneric: "Genérico",
    compRow1: "Multi-vertical (20+ tipos de espacio)",
    compRow2: "Totalmente en Portugués (PT)",
    compRow3: "Sitio web público personalizable",
    compRow4: "App móvil nativa",
    compRow5: "MBWay & Multibanco",
    compRow6: "SAF-T & ATCUD (Portugal)",
    compRow7: "AI Insights & Recomendaciones",
    compRow8: "API Abierta & Integraciones",
    testimonialsTitle: "Lo que dicen",
    testimonialsTitleHighlight: "nuestros clientes",
    testimonialsBadge: "Testimonios",
    t1quote: "Desde que cambiamos a Vytal, ahorramos 3 horas al día en tareas administrativas. Los pagos automáticos via MBWay cambiaron completamente nuestro flujo de caja.",
    t1name: "Ana Ferreira", t1role: "Propietaria", t1gym: "CrossFit Aveiro",
    t2quote: "El CRM de leads es increíble. Antes perdíamos potenciales miembros porque no teníamos seguimiento. Ahora convertimos un 40% más de leads en miembros de pago.",
    t2name: "Ricardo Santos", t2role: "Head Coach & Manager", t2gym: "Iron Temple Lisboa",
    t3quote: "Gestionamos 3 estudios de yoga con Vytal. La funcionalidad multi-ubicación es fantástica y el sitio web personalizado para cada estudio aumentó nuestras inscripciones en un 60%.",
    t3name: "Sofia Maia", t3role: "Directora", t3gym: "Studio Zen — 3 locales",
    pricingTitle: "Simple y",
    pricingTitleHighlight: "transparente",
    pricingSubtitle: "Sin sorpresas, sin costes ocultos. Cambia de plan cuando quieras.",
    pricingBadge: "Precios",
    monthly: "Mensual",
    annual: "Anual",
    mostPopular: "Más Popular",
    onRequest: "Bajo consulta",
    billedAnnually: "Facturado anualmente · Ahorra",
    perYear: "€/año",
    pricingNote: "Sin tarjeta de crédito para empezar · Cancela cuando quieras · Soporte en Portugués",
    planFreeDesc: "Para empezar sin compromiso.",
    planProDesc: "Para espacios en crecimiento.",
    planEnterpriseDesc: "Para redes y franquicias fitness.",
    planFreePeriod: "para siempre",
    planProPeriod: "por mes",
    planEnterprisePeriod: "personalizado",
    planFreeF1: "Hasta 20 miembros", planFreeF2: "1 ubicación", planFreeF3: "Calendario de clases",
    planFreeF4: "Perfiles básicos", planFreeF5: "App móvil (solo lectura)", planFreeF6: "Soporte por email",
    planFreeN1: "Pagos automáticos", planFreeN2: "CRM avanzado", planFreeN3: "Sitio web público", planFreeN4: "API",
    planProF1: "Miembros ilimitados", planProF2: "1 ubicación", planProF3: "Todas las funcionalidades",
    planProF4: "Sitio web público personalizado", planProF5: "Pagos MBWay & SEPA", planProF6: "SAF-T & ATCUD",
    planProF7: "CRM & Leads", planProF8: "App móvil completa", planProF9: "Soporte prioritario",
    planProN1: "Multi-ubicación", planProN2: "API Abierta",
    planEntF1: "Multi-ubicación", planEntF2: "Miembros ilimitados", planEntF3: "API Abierta & Webhooks",
    planEntF4: "Integraciones personalizadas", planEntF5: "Soporte dedicado 24/7", planEntF6: "Onboarding asistido",
    planEntF7: "SLA garantizado", planEntF8: "Facturación centralizada",
    planFreeCta: "Empezar Gratis", planProCta: "Empezar Gratis 14 días", planEntCta: "Hablar con Ventas",
    faqTitle: "Preguntas",
    faqTitleHighlight: "frecuentes",
    faqBadge: "FAQ",
    faq1q: "¿Vytal funciona para yoga, pilates, artes marciales y otros tipos de espacio?",
    faq1a: "¡Sí! Vytal soporta 20+ tipos de espacios fitness y wellness, incluyendo CrossFit, yoga, pilates, artes marciales, natación, gimnasios tradicionales, entrenadores personales, estudios de danza y mucho más. Cada vertical tiene su propia configuración y terminología.",
    faq2q: "¿Puedo migrar mi espacio desde Regibox u otro software?",
    faq2a: "Absolutamente. Tenemos un equipo de onboarding dedicado que ayuda en la migración de datos (miembros, pagos, historial) desde cualquier plataforma anterior. La migración es gratuita en los planes Pro y Enterprise y normalmente tarda menos de 48 horas.",
    faq3q: "¿El sitio público de mi espacio es totalmente personalizable?",
    faq3a: "Sí. Cada espacio tiene su propio subdominio (vytal.fit/mi-gimnasio) o puede usar su propio dominio. Puedes personalizar colores, logo, fotos, textos, horarios, precios y mucho más — sin necesitar conocimientos técnicos.",
    faq4q: "¿Qué métodos de pago están soportados?",
    faq4a: "Soportamos MBWay, referencias Multibanco, transferencia SEPA, tarjeta de crédito/débito y débito directo. Para el mercado portugués, generamos SAF-T y ATCUD conformes con la AT. Próximamente también PayPal y Apple Pay.",
    faq5q: "¿Existe una app móvil para los atletas?",
    faq5a: "Sí, la app Vytal está disponible para iOS (App Store) y Android (Google Play). Los atletas pueden hacer check-in, consultar WODs, ver su progreso, hacer reservas y comunicarse con sus coaches directamente desde la app.",
    faq6q: "¿Vytal cumple con el RGPD (Reglamento General de Protección de Datos)?",
    faq6a: "Totalmente. Todos los datos están alojados en la Unión Europea (Portugal/Irlanda), con encriptación end-to-end, control de accesos por perfil, registro de consentimientos, derecho al olvido y exportación de datos. Proporcionamos DPA (Acuerdo de Procesamiento de Datos) para todos los clientes.",
    ctaBannerBadge: "Sin tarjeta de crédito",
    ctaBannerTitle: "¿Listo para transformar",
    ctaBannerTitleLine2: "tu espacio?",
    ctaBannerSubtitle: "Empieza gratis hoy. Configura tu espacio en menos de 5 minutos. Sin compromiso, sin tarjeta de crédito.",
    ctaBannerStart: "Empezar Gratis Ahora",
    ctaBannerDemo: "Ver Demo en Vivo",
    footerTagline: "La plataforma de gestión para espacios fitness y wellness — hecha en Portugal, para el mundo.",
    footerRights: "Todos los derechos reservados. Hecho con",
    footerInPortugal: "en Portugal.",
    footerAllSystems: "Todos los sistemas operativos",
    footerProduct: "Producto", footerResources: "Recursos", footerCompany: "Empresa", footerLegal: "Legal",
    fpFeat: "Funcionalidades", fpPricing: "Precios", fpNews: "Novedades", fpRoadmap: "Roadmap", fpApi: "API Docs",
    frHelp: "Centro de Ayuda", frBlog: "Blog", frVideos: "Tutoriales en Vídeo", frBrand: "Marca", frStatus: "Estado del Sistema",
    fcAbout: "Sobre Nosotros", fcCareers: "Carreras", fcPartners: "Socios", fcPress: "Prensa", fcContact: "Contacto",
    flTerms: "Términos de Servicio", flPrivacy: "Política de Privacidad", flRgpd: "RGPD", flCookies: "Cookies", flDpa: "DPA",
    tabAdmin: "Admin", tabWebsite: "Sitio Web", tabMembro: "Miembro", tabMobile: "Móvil",
    tabAdminTitle: "Panel de control completo",
    tabAdminDesc: "Una visión 360° de tu espacio. Dashboards en tiempo real, gestión de miembros, finanzas y mucho más — todo en un solo lugar.",
    tabAdminI1: "Dashboard", tabAdminI2: "Miembros", tabAdminI3: "Clases", tabAdminI4: "CRM", tabAdminI5: "Finanzas", tabAdminI6: "Informes",
    tabWebsiteTitle: "Sitio público personalizable",
    tabWebsiteDesc: "Cada espacio tiene su sitio con dominio propio, colores de marca, horarios en vivo, tienda y formulario de contacto.",
    tabWebsiteI1: "Página Principal", tabWebsiteI2: "Horarios", tabWebsiteI3: "Planes", tabWebsiteI4: "Instructores", tabWebsiteI5: "Tienda", tabWebsiteI6: "Contacto",
    tabMembroTitle: "Portal del atleta",
    tabMembroDesc: "Tus miembros acceden online para ver horarios, hacer reservas, consultar resultados y gestionar su suscripción.",
    tabMembroI1: "Mis Clases", tabMembroI2: "Resultados", tabMembroI3: "Plan", tabMembroI4: "Pagos", tabMembroI5: "Perfil", tabMembroI6: "Progreso",
    tabMobileTitle: "App para iOS y Android",
    tabMobileDesc: "Los atletas llevan el gimnasio en el bolsillo. Check-in, entrenamientos, resultados y comunicaciones — todo en la app Vytal.",
    tabMobileI1: "WOD de Hoy", tabMobileI2: "Check-in", tabMobileI3: "Leaderboard", tabMobileI4: "Entrenamientos", tabMobileI5: "Mensajes", tabMobileI6: "Progreso",
    // Verticals
    verticalsTitle: "Un producto.",
    verticalsTitleHighlight: "20 verticales.",
    verticalsSubtitle: "De la box de CrossFit al estudio de danza — Vytal se adapta a tu negocio.",
    v_crossfit_box: "CrossFit Box",
    v_functional_training: "Entrenamiento Funcional",
    v_gym: "Gimnasio",
    v_yoga_studio: "Estudio de Yoga",
    v_pilates_studio: "Estudio de Pilates",
    v_martial_arts: "Artes Marciales",
    v_personal_training: "Entrenamiento Personal",
    v_swimming: "Natación",
    v_dance_studio: "Estudio de Danza",
    v_health_club: "Health Club",
    v_sports_club: "Club Deportivo",
    v_climbing_gym: "Gimnasio de Escalada",
    v_cycling_studio: "Estudio de Cycling",
    v_running_club: "Club de Running",
    v_gymnastics_academy: "Academia de Gimnasia",
    v_rehabilitation: "Rehabilitación",
    v_weightlifting_club: "Club de Halterofilia",
    v_bootcamp: "Bootcamp",
    v_surf_water_sports: "Surf & Deportes Acuáticos",
    v_other: "Otro",
    // Feature Deep Dive
    deepDiveBadge: "Funcionalidades en detalle",
    deepDiveCheckinTitle: "Check-in inteligente",
    deepDiveCheckinDesc: "Elimina las colas y el papel. El check-in es instantáneo, preciso e integrado con asistencia y pagos.",
    deepDiveCheckinB1: "Código QR único por atleta",
    deepDiveCheckinB2: "Check-in masivo para coaches",
    deepDiveCheckinB3: "Walk-in sin reserva previa",
    deepDiveCheckinB4: "Seguimiento automático de no-shows",
    deepDiveCrmTitle: "CRM & Pipeline de ventas",
    deepDiveCrmDesc: "Convierte más leads en miembros de pago con un pipeline visual y seguimientos automáticos.",
    deepDiveCrmB1: "Kanban drag-and-drop intuitivo",
    deepDiveCrmB2: "Lead scoring automático",
    deepDiveCrmB3: "Rastreo de fuente (Facebook, Google...)",
    deepDiveCrmB4: "Seguimiento automático por email/SMS",
    deepDiveWebsiteTitle: "Website builder completo",
    deepDiveWebsiteDesc: "Tu espacio merece una presencia digital profesional. Configúralo en minutos, sin código.",
    deepDiveWebsiteB1: "Dominio propio incluido",
    deepDiveWebsiteB2: "6 páginas: Inicio, Horarios, Planes, Equipo, Tienda, Contacto",
    deepDiveWebsiteB3: "Tienda online con carrito de compras",
    deepDiveWebsiteB4: "SEO, analytics y testimonios integrados",
    deepDiveAnalyticsTitle: "Informes & Analytics",
    deepDiveAnalyticsDesc: "Toma decisiones basadas en datos reales. Ve qué funciona y corrige lo que no.",
    deepDiveAnalyticsB1: "Heatmap de asistencia por hora/día",
    deepDiveAnalyticsB2: "Gráficos de ingresos y crecimiento",
    deepDiveAnalyticsB3: "Predicción de churn con IA",
    deepDiveAnalyticsB4: "Análisis de retención de miembros",
    // Payments
    paymentsTitle: "Pagos para",
    paymentsTitleHighlight: "Portugal",
    paymentsBadge: "Pagos",
    paymentsSubtitle: "Todos los métodos de pago que usan tus clientes — integrados desde el inicio.",
    paymentsMbway: "MB Way",
    paymentsMultibanco: "Multibanco",
    paymentsSepa: "SEPA",
    paymentsVisa: "Visa / MC",
    paymentsCash: "Efectivo",
    paymentsTransfer: "Transferencia",
    // Automations & AI
    autoTitle: "Automatizaciones &",
    autoTitleHighlight: "Inteligencia Artificial",
    autoBadge: "Automatizaciones & IA",
    autoSubtitle: "Ahorra horas por semana con automatizaciones inteligentes e insights generados por IA.",
    autoColLeft: "Automatizaciones",
    autoColRight: "AI Insights",
    autoA1Title: "Emails de hito", autoA1Desc: "Felicitaciones automáticas al 1.er mes, 6 meses, 1 año como miembro.",
    autoA2Title: "Campañas anti-churn", autoA2Desc: "Detecta miembros en riesgo y envía ofertas personalizadas.",
    autoA3Title: "Onboarding secuenciado", autoA3Desc: "Secuencia automática de bienvenida para nuevos miembros.",
    autoA4Title: "Mensajes de cumpleaños", autoA4Desc: "Felicita automáticamente en el día de cumpleaños del miembro.",
    autoB1Title: "Predicción de churn", autoB1Desc: "La IA identifica miembros que pueden cancelar en las próximas semanas.",
    autoB2Title: "Agendamiento inteligente", autoB2Desc: "Sugiere los mejores horarios basándose en la demanda histórica.",
    autoB3Title: "Sugerencia de WODs", autoB3Desc: "Recomienda entrenamientos adaptados al nivel e historial de cada atleta.",
    autoB4Title: "Readiness scoring", autoB4Desc: "Evalúa la disposición del atleta en base a entrenamientos y recuperación.",
    // Compliance
    complianceTitle: "Compliance &",
    complianceTitleHighlight: "Seguridad",
    complianceBadge: "Seguridad",
    complianceSubtitle: "Construido para cumplir los requisitos legales portugueses y europeos.",
    complianceRgpd: "RGPD Compliant",
    complianceSaft: "SAF-T / ATCUD Ready",
    complianceSsl: "SSL Encriptado",
    complianceUptime: "99.9% Uptime",
    complianceIso: "ISO 27001 (planificado)",
    complianceBackup: "Backups Diarios",
  },
};
